<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>026680b6-6d33-4db2-af6f-9b63e87ced02</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.9.0" />
  </ItemGroup>

</Project>
